version: '2'

services:
  angular-front:
    image: 'angular-knfc-frontend:2.0.0'
    build:
      # context: Frontend-Knife/dist/knfc_frontend
      context: Frontend-Knife
    container_name: knfc-frontend-angular-2
    restart: always
    ports:
      - "3013:3013"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  knfc-backend:
    image: 'knfc-backend-spring-boot:2.0.0'
    build:
      context: Backend-Knife
    container_name: knfc-backend-spring-boot-2
    restart: always
    ports:
      - "8093:8093"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro