server.servlet.context-path=/
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=clubknife@yandex.ru
spring.mail.password=qhnzyrojjxiofjmr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate = true
spring.flyway.ignoreMissingMigrations=true
spring.jpa.open-in-view=false
application.days_count=21

#KnifeClub settings
server.port=8093
spring.datasource.url=jdbc:postgresql://92.255.237.68:5432/knfc?currentSchema=knfc
spring.datasource.password=@8acJMQKc
cors.allowedOrigins=https://knifeclub43.ru
mail.to=clubknife@yandex.ru

#Local settings
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5433/knife?currentSchema=knfc
#spring.datasource.password=123
#spring.mail.username=nikolaylisk5999@gmail.com
#spring.mail.password=game wtnk wkqr gsuz
#cors.allowedOrigins=http://192.168.0.106:4200
#mail.to=kolyan-59@yandex.ru